debug = false

logLevel = "INFO"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "appliance.local"
watch = true
exposedByDefault = false

[acme]
email = "admin@appliance.local"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"

[traefikLog]
filePath = "/var/log/traefik-service.log"

[accessLog]
filePath = "/var/log/traefik-access.log"

[web]
address = ":8099"
#  [web.auth.basic]
#    users = ["admin:$apr1$BlhHsA7Y$em2OjpetSBca3P4zDCv3X0"]
